#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_baza_test")]
	public partial class bazaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSAMOCHODY(SAMOCHODY instance);
    partial void UpdateSAMOCHODY(SAMOCHODY instance);
    partial void DeleteSAMOCHODY(SAMOCHODY instance);
    #endregion
		
		public bazaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["db_baza_testConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public bazaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public bazaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public bazaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public bazaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PALIWO> PALIWOs
		{
			get
			{
				return this.GetTable<PALIWO>();
			}
		}
		
		public System.Data.Linq.Table<SAMOCHODY> SAMOCHODies
		{
			get
			{
				return this.GetTable<SAMOCHODY>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PALIWO")]
	public partial class PALIWO
	{
		
		private int _Id;
		
		private System.Nullable<bool> _Benzyna;
		
		private System.Nullable<bool> _Gas;
		
		private System.Nullable<bool> _Olej_Napedowy;
		
		public PALIWO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Benzyna", DbType="Bit")]
		public System.Nullable<bool> Benzyna
		{
			get
			{
				return this._Benzyna;
			}
			set
			{
				if ((this._Benzyna != value))
				{
					this._Benzyna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gas", DbType="Bit")]
		public System.Nullable<bool> Gas
		{
			get
			{
				return this._Gas;
			}
			set
			{
				if ((this._Gas != value))
				{
					this._Gas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Olej_Napedowy", DbType="Bit")]
		public System.Nullable<bool> Olej_Napedowy
		{
			get
			{
				return this._Olej_Napedowy;
			}
			set
			{
				if ((this._Olej_Napedowy != value))
				{
					this._Olej_Napedowy = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SAMOCHODY")]
	public partial class SAMOCHODY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Marka;
		
		private string _Model;
		
		private string _Kolor;
		
		private System.Nullable<int> _Przebieg;
		
		private System.Nullable<bool> _Klima;
		
		private System.Nullable<bool> _Garazowany;
		
		private System.Nullable<short> _Ilosc_Drzwi;
		
		private System.Nullable<int> _Ilosc_Koni;
		
		private System.Nullable<int> _Cena;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMarkaChanging(string value);
    partial void OnMarkaChanged();
    partial void OnModelChanging(string value);
    partial void OnModelChanged();
    partial void OnKolorChanging(string value);
    partial void OnKolorChanged();
    partial void OnPrzebiegChanging(System.Nullable<int> value);
    partial void OnPrzebiegChanged();
    partial void OnKlimaChanging(System.Nullable<bool> value);
    partial void OnKlimaChanged();
    partial void OnGarazowanyChanging(System.Nullable<bool> value);
    partial void OnGarazowanyChanged();
    partial void OnIlosc_DrzwiChanging(System.Nullable<short> value);
    partial void OnIlosc_DrzwiChanged();
    partial void OnIlosc_KoniChanging(System.Nullable<int> value);
    partial void OnIlosc_KoniChanged();
    partial void OnCenaChanging(System.Nullable<int> value);
    partial void OnCenaChanged();
    #endregion
		
		public SAMOCHODY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marka", DbType="NVarChar(50)")]
		public string Marka
		{
			get
			{
				return this._Marka;
			}
			set
			{
				if ((this._Marka != value))
				{
					this.OnMarkaChanging(value);
					this.SendPropertyChanging();
					this._Marka = value;
					this.SendPropertyChanged("Marka");
					this.OnMarkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="NVarChar(50)")]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this.OnModelChanging(value);
					this.SendPropertyChanging();
					this._Model = value;
					this.SendPropertyChanged("Model");
					this.OnModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kolor", DbType="NVarChar(50)")]
		public string Kolor
		{
			get
			{
				return this._Kolor;
			}
			set
			{
				if ((this._Kolor != value))
				{
					this.OnKolorChanging(value);
					this.SendPropertyChanging();
					this._Kolor = value;
					this.SendPropertyChanged("Kolor");
					this.OnKolorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Przebieg", DbType="Int")]
		public System.Nullable<int> Przebieg
		{
			get
			{
				return this._Przebieg;
			}
			set
			{
				if ((this._Przebieg != value))
				{
					this.OnPrzebiegChanging(value);
					this.SendPropertyChanging();
					this._Przebieg = value;
					this.SendPropertyChanged("Przebieg");
					this.OnPrzebiegChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Klima", DbType="Bit")]
		public System.Nullable<bool> Klima
		{
			get
			{
				return this._Klima;
			}
			set
			{
				if ((this._Klima != value))
				{
					this.OnKlimaChanging(value);
					this.SendPropertyChanging();
					this._Klima = value;
					this.SendPropertyChanged("Klima");
					this.OnKlimaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Garazowany", DbType="Bit")]
		public System.Nullable<bool> Garazowany
		{
			get
			{
				return this._Garazowany;
			}
			set
			{
				if ((this._Garazowany != value))
				{
					this.OnGarazowanyChanging(value);
					this.SendPropertyChanging();
					this._Garazowany = value;
					this.SendPropertyChanged("Garazowany");
					this.OnGarazowanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilosc_Drzwi", DbType="SmallInt")]
		public System.Nullable<short> Ilosc_Drzwi
		{
			get
			{
				return this._Ilosc_Drzwi;
			}
			set
			{
				if ((this._Ilosc_Drzwi != value))
				{
					this.OnIlosc_DrzwiChanging(value);
					this.SendPropertyChanging();
					this._Ilosc_Drzwi = value;
					this.SendPropertyChanged("Ilosc_Drzwi");
					this.OnIlosc_DrzwiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilosc_Koni", DbType="Int")]
		public System.Nullable<int> Ilosc_Koni
		{
			get
			{
				return this._Ilosc_Koni;
			}
			set
			{
				if ((this._Ilosc_Koni != value))
				{
					this.OnIlosc_KoniChanging(value);
					this.SendPropertyChanging();
					this._Ilosc_Koni = value;
					this.SendPropertyChanged("Ilosc_Koni");
					this.OnIlosc_KoniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cena", DbType="Int")]
		public System.Nullable<int> Cena
		{
			get
			{
				return this._Cena;
			}
			set
			{
				if ((this._Cena != value))
				{
					this.OnCenaChanging(value);
					this.SendPropertyChanging();
					this._Cena = value;
					this.SendPropertyChanged("Cena");
					this.OnCenaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
